# Generated by Django 3.2.5 on 2022-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_auction_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active_auction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
