# Generated by Django 3.2.5 on 2022-05-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220503_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='active_auction',
            new_name='state',
        ),
    ]
