# Generated by Django 3.2.5 on 2022-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20220504_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('toys', 'Toys'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('books', 'Books'), ('sports', 'Sports'), ('home', 'Home'), ('music', 'Music')], max_length=15),
        ),
    ]
